<MyRoot>:
  BoxLayout:
    orientation: 'vertical'
    Label:
      text: "TRK"
      font_size: 64
      color: 0.92, 0.45, 0
      size_hint: 1, 0.3
    Button:
      text: "Acc"
      font_size: 32
      size_hint: 1, 0.175
    Button:
      text: "Speed"
      font_size: 32
      size_hint: 1, 0.175
    Button:
      text: "Barpath"
      font_size: 32
      size_hint: 1, 0.175
    BoxLayout:
      size_hint: 1, 0.175
      orientation: 'horizontal'
      Button:
        text: "H"
        font_size: 32
        size_hint: 0.5, 1
      Button:
        text: "BT"
        font_size: 32
        size_hint: 0.5, 1
