<MenuScreen>:
  speed_label: speed_label

  FloatLayout:
    name: 'menu'

    RoundedButton:
      text: "BT"
      on_press: root.connect()
      
      font_size: 32

      size_hint: 75/root.window_size[0], 75/root.window_size[1]
      pos_hint: {"x": 25/root.window_size[0], "y": 1-100/root.window_size[1]}

    Label:
      text: "TRK"

      font_size: 64
      size_hint: 75/root.window_size[0], 75/root.window_size[1]
      pos_hint: {"center_x": 0.5, "y": 1-100/root.window_size[1]}

      background_color: (0/255, 55/255, 110/255, 1.0)
    
    Label:
      id: speed_label
      font_size: 48
      text: "Connect BT"
  
<RoundedButton@Button>
  background_color: 0,0,0,0
  background_normal: ''
  canvas.before:
    Color:
      rgba: (0/255, 55/255, 110/255, 1.0)
    RoundedRectangle:
      size: self.size
      pos: self.pos
      radius: [38]